In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("assets/vgsales.csv")

df.head()
print(df.dtypes)
#print(df.shape)
#df=df.replace('N/A','null',inplace=True)

df.head()

Rank              int64
Name             object
Platform         object
Year            float64
Genre            object
Publisher        object
NA_Sales        float64
EU_Sales        float64
JP_Sales        float64
Other_Sales     float64
Global_Sales    float64
dtype: object

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [3]:
df_2 = df.replace('N/A', None).dropna()
df_2['Platform'] = df_2['Platform'].replace('2600', None)
df_2=df_2.dropna(subset=['Platform']).reset_index(drop=True)

acr_dict={
'Wii':'Nintendo Wii',
'WiiU':'Nintendo Wii U',
'X360':'Microsoft Xbox 360',
'SNES':'Super Nintendo Entertainment System',
'NES':'Nintendo Entertainment System',
'GEN':'Sega Genesis',
'DC':'Sega Dreamcast',
'3DO': '3DO Multiplayer',
'PSV':'Sony Playstation Vita',
'SAT': 'Sega Saturn',
'SCD': 'Sega CD',
'WS': 'Bandai WonderSwan',
'NG': 'SNK Neo Geo',
'TG16': 'NEC TurboGrafx-16t',
'GB': 'Nintendo Game Boy',
'3DS': 'Nintendo 3DS',
'GBA': 'Nintendo Game Boy Advance',
'N64': 'Nintendo 64',
'DS': 'Nintendo DS',
'PS': 'Sony PlayStation',
'PS2': 'Sony PlayStation 2',
'PS3': 'Sony PlayStation 3',
'PS4': 'Sony PlayStation 4',
'XB': 'Microsoft Xbox',
'XOne': 'Microsoft Xbox One',
'GC': 'Nintendo GameCube',
'PSP': 'Sony PlayStation Portable',
'GG': 'Sega Game Gear',
'PCFX': 'NEC PC-FX',
}

df_2['Platform']=df_2['Platform'].replace(acr_dict)
df_2['Year']=df_2['Year'].astype(int)

df_2.head()
df_2.to_csv('Video_Game_sales.csv')